<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['name_ar' => 'مصر', 'name_en' => 'Egypt', 'code' => 'EG', 'currency_ar' => 'جنيه مصري', 'currency_en' => 'Egyptian Pound', 'currency_code' => 'EGP'],
            ['name_ar' => 'الولايات المتحدة', 'name_en' => 'United States', 'code' => 'US', 'currency_ar' => 'دولار أمريكي', 'currency_en' => 'US Dollar', 'currency_code' => 'USD'],
            ['name_ar' => 'فرنسا', 'name_en' => 'France', 'code' => 'FR', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'ألمانيا', 'name_en' => 'Germany', 'code' => 'DE', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'إيطاليا', 'name_en' => 'Italy', 'code' => 'IT', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'إسبانيا', 'name_en' => 'Spain', 'code' => 'ES', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'كندا', 'name_en' => 'Canada', 'code' => 'CA', 'currency_ar' => 'دولار كندي', 'currency_en' => 'Canadian Dollar', 'currency_code' => 'CAD'],
            ['name_ar' => 'أستراليا', 'name_en' => 'Australia', 'code' => 'AU', 'currency_ar' => 'دولار أسترالي', 'currency_en' => 'Australian Dollar', 'currency_code' => 'AUD'],
            ['name_ar' => 'اليابان', 'name_en' => 'Japan', 'code' => 'JP', 'currency_ar' => 'ين ياباني', 'currency_en' => 'Japanese Yen', 'currency_code' => 'JPY'],
            ['name_ar' => 'الصين', 'name_en' => 'China', 'code' => 'CN', 'currency_ar' => 'يوان صيني', 'currency_en' => 'Chinese Yuan', 'currency_code' => 'CNY'],
            ['name_ar' => 'البرازيل', 'name_en' => 'Brazil', 'code' => 'BR', 'currency_ar' => 'ريال برازيلي', 'currency_en' => 'Brazilian Real', 'currency_code' => 'BRL'],
            ['name_ar' => 'المكسيك', 'name_en' => 'Mexico', 'code' => 'MX', 'currency_ar' => 'بيزو مكسيكي', 'currency_en' => 'Mexican Peso', 'currency_code' => 'MXN'],
            ['name_ar' => 'روسيا', 'name_en' => 'Russia', 'code' => 'RU', 'currency_ar' => 'روبل روسي', 'currency_en' => 'Russian Ruble', 'currency_code' => 'RUB'],
            ['name_ar' => 'الهند', 'name_en' => 'India', 'code' => 'IN', 'currency_ar' => 'روبية هندية', 'currency_en' => 'Indian Rupee', 'currency_code' => 'INR'],
            ['name_ar' => 'جنوب إفريقيا', 'name_en' => 'South Africa', 'code' => 'ZA', 'currency_ar' => 'راند جنوب أفريقي', 'currency_en' => 'South African Rand', 'currency_code' => 'ZAR'],
            ['name_ar' => 'السويد', 'name_en' => 'Sweden', 'code' => 'SE', 'currency_ar' => 'كرونة سويدية', 'currency_en' => 'Swedish Krona', 'currency_code' => 'SEK'],
            ['name_ar' => 'سويسرا', 'name_en' => 'Switzerland', 'code' => 'CH', 'currency_ar' => 'فرنك سويسري', 'currency_en' => 'Swiss Franc', 'currency_code' => 'CHF'],
            ['name_ar' => 'الأرجنتين', 'name_en' => 'Argentina', 'code' => 'AR', 'currency_ar' => 'بيزو أرجنتيني', 'currency_en' => 'Argentine Peso', 'currency_code' => 'ARS'],
            ['name_ar' => 'النرويج', 'name_en' => 'Norway', 'code' => 'NO', 'currency_ar' => 'كرونة نرويجية', 'currency_en' => 'Norwegian Krone', 'currency_code' => 'NOK'],
            ['name_ar' => 'اليونان', 'name_en' => 'Greece', 'code' => 'GR', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'بولندا', 'name_en' => 'Poland', 'code' => 'PL', 'currency_ar' => 'زلوطي بولندي', 'currency_en' => 'Polish Zloty', 'currency_code' => 'PLN'],
            ['name_ar' => 'إندونيسيا', 'name_en' => 'Indonesia', 'code' => 'ID', 'currency_ar' => 'روبية إندونيسية', 'currency_en' => 'Indonesian Rupiah', 'currency_code' => 'IDR'],
            ['name_ar' => 'ماليزيا', 'name_en' => 'Malaysia', 'code' => 'MY', 'currency_ar' => 'رينغيت ماليزي', 'currency_en' => 'Malaysian Ringgit', 'currency_code' => 'MYR'],
            ['name_ar' => 'فيتنام', 'name_en' => 'Vietnam', 'code' => 'VN', 'currency_ar' => 'دونغ فيتنامي', 'currency_en' => 'Vietnamese Dong', 'currency_code' => 'VND'],
            ['name_ar' => 'تشيلي', 'name_en' => 'Chile', 'code' => 'CL', 'currency_ar' => 'بيزو تشيلي', 'currency_en' => 'Chilean Peso', 'currency_code' => 'CLP'],
            ['name_ar' => 'كولومبيا', 'name_en' => 'Colombia', 'code' => 'CO', 'currency_ar' => 'بيزو كولومبي', 'currency_en' => 'Colombian Peso', 'currency_code' => 'COP'],
            ['name_ar' => 'بيرو', 'name_en' => 'Peru', 'code' => 'PE', 'currency_ar' => 'سول بيروفي', 'currency_en' => 'Peruvian Sol', 'currency_code' => 'PEN'],
            ['name_ar' => 'أوروغواي', 'name_en' => 'Uruguay', 'code' => 'UY', 'currency_ar' => 'بيزو أوروغوياني', 'currency_en' => 'Uruguayan Peso', 'currency_code' => 'UYU'],
            ['name_ar' => 'سنغافورة', 'name_en' => 'Singapore', 'code' => 'SG', 'currency_ar' => 'دولار سنغافوري', 'currency_en' => 'Singapore Dollar', 'currency_code' => 'SGD'],
            ['name_ar' => 'تركيا', 'name_en' => 'Turkey', 'code' => 'TR', 'currency_ar' => 'ليرة تركية', 'currency_en' => 'Turkish Lira', 'currency_code' => 'TRY'],
            ['name_ar' => 'سريلانكا', 'name_en' => 'Sri Lanka', 'code' => 'LK', 'currency_ar' => 'روبية سريلانكية', 'currency_en' => 'Sri Lankan Rupee', 'currency_code' => 'LKR'],
            ['name_ar' => 'لبنان', 'name_en' => 'Lebanon', 'code' => 'LB', 'currency_ar' => 'ليرة لبنانية', 'currency_en' => 'Lebanese Pound', 'currency_code' => 'LBP'],
            ['name_ar' => 'الأردن', 'name_en' => 'Jordan', 'code' => 'JO', 'currency_ar' => 'دينار أردني', 'currency_en' => 'Jordanian Dinar', 'currency_code' => 'JOD'],
            ['name_ar' => 'العراق', 'name_en' => 'Iraq', 'code' => 'IQ', 'currency_ar' => 'دينار عراقي', 'currency_en' => 'Iraqi Dinar', 'currency_code' => 'IQD'],
            ['name_ar' => 'السعودية', 'name_en' => 'Saudi Arabia', 'code' => 'SA', 'currency_ar' => 'ريال سعودي', 'currency_en' => 'Saudi Riyal', 'currency_code' => 'SAR'],
            ['name_ar' => 'الإمارات العربية المتحدة', 'name_en' => 'United Arab Emirates', 'code' => 'AE', 'currency_ar' => 'درهم إماراتي', 'currency_en' => 'UAE Dirham', 'currency_code' => 'AED'],
            ['name_ar' => 'قطر', 'name_en' => 'Qatar', 'code' => 'QA', 'currency_ar' => 'ريال قطري', 'currency_en' => 'Qatari Riyal', 'currency_code' => 'QAR'],
            ['name_ar' => 'الكويت', 'name_en' => 'Kuwait', 'code' => 'KW', 'currency_ar' => 'دينار كويتي', 'currency_en' => 'Kuwaiti Dinar', 'currency_code' => 'KWD'],
            ['name_ar' => 'عمان', 'name_en' => 'Oman', 'code' => 'OM', 'currency_ar' => 'ريال عماني', 'currency_en' => 'Omani Rial', 'currency_code' => 'OMR'],
            ['name_ar' => 'البحرين', 'name_en' => 'Bahrain', 'code' => 'BH', 'currency_ar' => 'دينار بحريني', 'currency_en' => 'Bahraini Dinar', 'currency_code' => 'BHD'],
            ['name_ar' => 'مالطا', 'name_en' => 'Malta', 'code' => 'MT', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'موناكو', 'name_en' => 'Monaco', 'code' => 'MC', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'سان مارينو', 'name_en' => 'San Marino', 'code' => 'SM', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'الفاتيكان', 'name_en' => 'Vatican City', 'code' => 'VA', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'الأراضي الفلسطينية', 'name_en' => 'Palestine', 'code' => 'PS', 'currency_ar' => 'شيكل إسرائيلي جديد', 'currency_en' => 'Israeli New Shekel', 'currency_code' => 'ILS'],
            ['name_ar' => 'سوريا', 'name_en' => 'Syria', 'code' => 'SY', 'currency_ar' => 'ليرة سورية', 'currency_en' => 'Syrian Pound', 'currency_code' => 'SYP'],
            ['name_ar' => 'اليمن', 'name_en' => 'Yemen', 'code' => 'YE', 'currency_ar' => 'ريال يمني', 'currency_en' => 'Yemeni Rial', 'currency_code' => 'YER'],
            ['name_ar' => 'إيران', 'name_en' => 'Iran', 'code' => 'IR', 'currency_ar' => 'ريال إيراني', 'currency_en' => 'Iranian Rial', 'currency_code' => 'IRR'],
            ['name_ar' => 'تركمانستان', 'name_en' => 'Turkmenistan', 'code' => 'TM', 'currency_ar' => 'منات تركماني', 'currency_en' => 'Turkmenistani Manat', 'currency_code' => 'TMT'],
            ['name_ar' => 'أوزبكستان', 'name_en' => 'Uzbekistan', 'code' => 'UZ', 'currency_ar' => 'سوم أوزبكي', 'currency_en' => 'Uzbekistani Som', 'currency_code' => 'UZS'],
            ['name_ar' => 'قرغيزستان', 'name_en' => 'Kyrgyzstan', 'code' => 'KG', 'currency_ar' => 'سوم قيرغيزي', 'currency_en' => 'Kyrgyzstani Som', 'currency_code' => 'KGS'],
            ['name_ar' => 'بيلاروس', 'name_en' => 'Belarus', 'code' => 'BY', 'currency_ar' => 'روبل بيلاروسي', 'currency_en' => 'Belarusian Ruble', 'currency_code' => 'BYN'],
            ['name_ar' => 'أوكرانيا', 'name_en' => 'Ukraine', 'code' => 'UA', 'currency_ar' => 'هريفنيا أوكرانية', 'currency_en' => 'Ukrainian Hryvnia', 'currency_code' => 'UAH'],
            ['name_ar' => 'مولدوفا', 'name_en' => 'Moldova', 'code' => 'MD', 'currency_ar' => 'ليو مولدوفي', 'currency_en' => 'Moldovan Leu', 'currency_code' => 'MDL'],
            ['name_ar' => 'أرمينيا', 'name_en' => 'Armenia', 'code' => 'AM', 'currency_ar' => 'درام أرميني', 'currency_en' => 'Armenian Dram', 'currency_code' => 'AMD'],
            ['name_ar' => 'جورجيا', 'name_en' => 'Georgia', 'code' => 'GE', 'currency_ar' => 'لاري جورجي', 'currency_en' => 'Georgian Lari', 'currency_code' => 'GEL'],
            ['name_ar' => 'إستونيا', 'name_en' => 'Estonia', 'code' => 'EE', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'لاتفيا', 'name_en' => 'Latvia', 'code' => 'LV', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'ليتوانيا', 'name_en' => 'Lithuania', 'code' => 'LT', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'مقدونيا', 'name_en' => 'North Macedonia', 'code' => 'MK', 'currency_ar' => 'دينار مقدوني', 'currency_en' => 'Macedonian Denar', 'currency_code' => 'MKD'],
            ['name_ar' => 'الجبل الأسود', 'name_en' => 'Montenegro', 'code' => 'ME', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'كوسوفو', 'name_en' => 'Kosovo', 'code' => 'XK', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'ألبانيا', 'name_en' => 'Albania', 'code' => 'AL', 'currency_ar' => 'ليك ألباني', 'currency_en' => 'Albanian Lek', 'currency_code' => 'ALL'],
            ['name_ar' => 'البوسنة والهرسك', 'name_en' => 'Bosnia and Herzegovina', 'code' => 'BA', 'currency_ar' => 'مارك بوسني', 'currency_en' => 'Bosnia and Herzegovina Convertible Mark', 'currency_code' => 'BAM'],
            ['name_ar' => 'كرواتيا', 'name_en' => 'Croatia', 'code' => 'HR', 'currency_ar' => ' kuna كرواتية', 'currency_en' => 'Croatian Kuna', 'currency_code' => 'HRK'],
            ['name_ar' => 'سلوفينيا', 'name_en' => 'Slovenia', 'code' => 'SI', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'سلوفاكيا', 'name_en' => 'Slovakia', 'code' => 'SK', 'currency_ar' => 'يورو', 'currency_en' => 'Euro', 'currency_code' => 'EUR'],
            ['name_ar' => 'هنغاريا', 'name_en' => 'Hungary', 'code' => 'HU', 'currency_ar' => 'فورنت مجري', 'currency_en' => 'Hungarian Forint', 'currency_code' => 'HUF'],
            ['name_ar' => 'جزر القمر', 'name_en' => 'Comoros', 'code' => 'KM', 'currency_ar' => 'فرنك قمري', 'currency_en' => 'Comorian Franc', 'currency_code' => 'KMF'],
            ['name_ar' => 'موريشيوس', 'name_en' => 'Mauritius', 'code' => 'MU', 'currency_ar' => 'روبية موريشيوسية', 'currency_en' => 'Mauritian Rupee', 'currency_code' => 'MUR'],
            ['name_ar' => 'مدغشقر', 'name_en' => 'Madagascar', 'code' => 'MG', 'currency_ar' => 'أرياري مدغشقري', 'currency_en' => 'Malagasy Ariary', 'currency_code' => 'MGA'],
            ['name_ar' => 'تنزانيا', 'name_en' => 'Tanzania', 'code' => 'TZ', 'currency_ar' => 'شيلينغ تنزاني', 'currency_en' => 'Tanzanian Shilling', 'currency_code' => 'TZS'],
            ['name_ar' => 'كينيا', 'name_en' => 'Kenya', 'code' => 'KE', 'currency_ar' => 'شيلينغ كيني', 'currency_en' => 'Kenyan Shilling', 'currency_code' => 'KES'],
            ['name_ar' => 'أوغندا', 'name_en' => 'Uganda', 'code' => 'UG', 'currency_ar' => 'شيلينغ أوغندي', 'currency_en' => 'Ugandan Shilling', 'currency_code' => 'UGX'],
            ['name_ar' => 'رواندا', 'name_en' => 'Rwanda', 'code' => 'RW', 'currency_ar' => 'فرنك رواندي', 'currency_en' => 'Rwandan Franc', 'currency_code' => 'RWF'],
            ['name_ar' => 'بوروندي', 'name_en' => 'Burundi', 'code' => 'BI', 'currency_ar' => 'فرنك بوروندي', 'currency_en' => 'Burundian Franc', 'currency_code' => 'BIF'],
            ['name_ar' => 'جزر سليمان', 'name_en' => 'Solomon Islands', 'code' => 'SB', 'currency_ar' => 'دولار جزر سليمان', 'currency_en' => 'Solomon Islands Dollar', 'currency_code' => 'SBD'],
            ['name_ar' => 'بابوا غينيا الجديدة', 'name_en' => 'Papua New Guinea', 'code' => 'PG', 'currency_ar' => 'كينا بابوا غينيا الجديدة', 'currency_en' => 'Papua New Guinean Kina', 'currency_code' => 'PGK'],
            ['name_ar' => 'تونغا', 'name_en' => 'Tonga', 'code' => 'TO', 'currency_ar' => 'بانغ', 'currency_en' => 'Tongan Paʻanga', 'currency_code' => 'TOP'],
            ['name_ar' => 'فيجي', 'name_en' => 'Fiji', 'code' => 'FJ', 'currency_ar' => 'دولار فيجي', 'currency_en' => 'Fijian Dollar', 'currency_code' => 'FJD'],
            ['name_ar' => 'نيوزيلندا', 'name_en' => 'New Zealand', 'code' => 'NZ', 'currency_ar' => 'دولار نيوزيلندي', 'currency_en' => 'New Zealand Dollar', 'currency_code' => 'NZD'],
            ['name_ar' => 'ساموا', 'name_en' => 'Samoa', 'code' => 'WS', 'currency_ar' => 'تالا ساموي', 'currency_en' => 'Samoan Tala', 'currency_code' => 'WST'],
            ['name_ar' => 'جزر كوك', 'name_en' => 'Cook Islands', 'code' => 'CK', 'currency_ar' => 'دولار جزر كوك', 'currency_en' => 'Cook Islands Dollar', 'currency_code' => 'CKD'],
            ['name_ar' => 'جزر تابعة لنيوزيلندا', 'name_en' => 'Niue', 'code' => 'NU', 'currency_ar' => 'دولار نيوزيلندي', 'currency_en' => 'New Zealand Dollar', 'currency_code' => 'NZD'],
            ['name_ar' => 'جزر بيتكيرن', 'name_en' => 'Pitcairn Islands', 'code' => 'PN', 'currency_ar' => 'دولار نيوزيلندي', 'currency_en' => 'New Zealand Dollar', 'currency_code' => 'NZD'],
            ['name_ar' => 'جزر فارو', 'name_en' => 'Faroe Islands', 'code' => 'FO', 'currency_ar' => 'كرونة فاروية', 'currency_en' => 'Faroese Króna', 'currency_code' => 'DKK'],
            ['name_ar' => 'جرينلاند', 'name_en' => 'Greenland', 'code' => 'GL', 'currency_ar' => 'كرونة دنماركية', 'currency_en' => 'Danish Krone', 'currency_code' => 'DKK'],
            ['name_ar' => 'أيسلندا', 'name_en' => 'Iceland', 'code' => 'IS', 'currency_ar' => 'كرونة آيسلندية', 'currency_en' => 'Icelandic Króna', 'currency_code' => 'ISK'],
        ];

        DB::table('countries')->insert($countries);
    }
}
